"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Heart, Info, Plus, Scale, ShieldCheck, Sparkles, Truck } from "lucide-react";
import type { Artwork } from "@/types";
import { LivingArtwork } from "@/components/motion/living-artwork";
import { ArtworkCard } from "./artwork-card";
import { money } from "@/components/site/catalog";
import { useExperience } from "@/components/site/experience-provider";

const materials = [{ name: "Archival paper", delta: -18000 }, { name: "Museum canvas", delta: 0 }, { name: "Premium framed", delta: 74000 }, { name: "Living digital edition", delta: 120000 }];
const sizes = [{ name: "Small · 18 × 24 in", factor: .62 }, { name: "Medium · 30 × 40 in", factor: 1 }, { name: "Statement · 45 × 60 in", factor: 1.58 }];

export function ArtworkDetail({ artwork, related }: { artwork: Artwork; related: Artwork[] }) {
  const [material, setMaterial] = useState(materials[1]); const [size, setSize] = useState(sizes[1]);
  const { favorites, compare, toggleFavorite, toggleCompare, addToCart, markViewed } = useExperience();
  useEffect(() => markViewed(artwork.id), [artwork.id, markViewed]);
  const displayPrice = useMemo(() => Math.max(25000, Math.round((artwork.priceCents + material.delta) * size.factor)), [artwork.priceCents, material, size]);
  const favored = favorites.includes(artwork.id); const comparing = compare.includes(artwork.id);
  return <>
    <section className="px-5 pb-20 pt-8 lg:px-10"><div className="mx-auto max-w-[1500px]"><Link href="/art" className="mb-8 inline-flex items-center gap-2 text-[10px] uppercase tracking-widest text-white/45"><ArrowLeft size={14}/>Return to catalog</Link><div className="grid gap-10 lg:grid-cols-[1.25fr_.75fr] lg:gap-16">
      <div><LivingArtwork artwork={artwork} className="min-h-[64vh] lg:min-h-[78vh]" priority/><div className="mt-3 flex items-center justify-between text-[9px] uppercase tracking-wider text-white/30"><span>Simulated catalog study · licensed demo media</span><span>Zoom & full-screen available in viewer</span></div></div>
      <div className="lg:pt-9"><p className="eyebrow text-[#c8a968]">{artwork.artist}</p><h1 className="mt-5 font-display text-6xl font-light leading-[.9]">{artwork.title}</h1><p className="mt-5 text-sm text-white/45">{artwork.medium} · {artwork.dimensions} · 2026</p><p className="mt-7 text-base leading-8 text-white/65">{artwork.curatorialStatement}</p><div className="mt-8 border-y border-white/10 py-6"><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-widest text-white/35">Configured price</p><p className="mt-2 font-display text-4xl">{money(displayPrice)}</p></div><span className={`rounded-full px-3 py-1 text-[9px] uppercase tracking-wider ${artwork.available ? "bg-emerald-500/10 text-emerald-300" : "bg-amber-500/10 text-amber-300"}`}>{artwork.available ? "Available" : "Waitlist"}</span></div><p className="mt-3 text-xs text-white/40">or from {money(Math.round(displayPrice / 12))}/month with a configurable payment plan</p></div>
      <fieldset className="mt-7"><legend className="text-[10px] uppercase tracking-widest text-white/45">Material</legend><div className="mt-3 grid grid-cols-2 gap-2">{materials.map((option) => <button key={option.name} onClick={() => setMaterial(option)} className={`border p-3 text-left text-[11px] ${material.name === option.name ? "border-[#c8a968] bg-[#c8a968]/8" : "border-white/12"}`}>{option.name}{option.name.includes("Living") && !artwork.living && <span className="mt-1 block text-[8px] text-white/35">Custom motion quote</span>}</button>)}</div></fieldset>
      <fieldset className="mt-6"><legend className="text-[10px] uppercase tracking-widest text-white/45">Scale</legend><select value={size.name} onChange={(event) => setSize(sizes.find((option) => option.name === event.target.value) || sizes[1])} className="mt-3 w-full border border-white/12 bg-[#15130f] p-4 text-xs">{sizes.map((option) => <option key={option.name}>{option.name}</option>)}</select></fieldset>
      <div className="mt-7 grid grid-cols-[1fr_auto_auto] gap-2"><button onClick={() => addToCart(artwork, { material: material.name, size: size.name })} disabled={!artwork.available} className="flex items-center justify-center gap-2 bg-[#c8a968] px-6 py-4 text-[10px] font-bold uppercase tracking-widest text-black disabled:opacity-40">{artwork.available ? <><Plus size={15}/>Add to cart</> : <><Check size={15}/>Join waitlist</>}</button><button onClick={() => toggleFavorite(artwork.id)} className="grid size-12 place-items-center border border-white/15" aria-label={favored ? "Remove from favorites" : "Save artwork"}><Heart size={17} className={favored ? "fill-[#d9bd7a] text-[#d9bd7a]" : ""}/></button><button onClick={() => toggleCompare(artwork.id)} className="grid size-12 place-items-center border border-white/15" aria-label={comparing ? "Remove from comparison" : "Compare artwork"}><Scale size={17} className={comparing ? "text-[#d9bd7a]" : ""}/></button></div>
      <div className="mt-3 grid grid-cols-2 gap-2"><Link href={`/preview?art=${artwork.slug}`} className="border border-white/15 p-3 text-center text-[10px] uppercase tracking-widest">Preview in a room</Link><Link href={`/concierge?art=${artwork.slug}`} className="flex items-center justify-center gap-2 border border-white/15 p-3 text-[10px] uppercase tracking-widest"><Sparkles size={13}/>Ask Seraphina</Link></div>
      <div className="mt-8 grid gap-4 border-t border-white/10 pt-6 text-xs text-white/45 sm:grid-cols-3 lg:grid-cols-1 xl:grid-cols-3"><p className="flex items-start gap-2"><Truck size={16} className="shrink-0 text-[#c8a968]"/>Ships in 7–12 business days</p><p className="flex items-start gap-2"><ShieldCheck size={16} className="shrink-0 text-[#c8a968]"/>Recorded provenance</p><p className="flex items-start gap-2"><Info size={16} className="shrink-0 text-[#c8a968]"/>{artwork.commercialLicense ? "Commercial license eligible" : "Personal display license"}</p></div>
      </div></div></div></section>
    <section className="border-y border-white/10 bg-[#13110e] px-5 py-20 lg:px-10"><div className="mx-auto grid max-w-6xl gap-12 md:grid-cols-2"><div><p className="eyebrow text-[#c8a968]">About the work</p><h2 className="mt-4 font-display text-4xl">Material, intention, presence</h2><p className="mt-6 text-sm leading-8 text-white/55">{artwork.description}</p></div><div><p className="eyebrow text-[#c8a968]">Provenance</p><p className="mt-6 text-sm leading-8 text-white/55">{artwork.provenance}</p><dl className="mt-7 grid grid-cols-2 gap-5 text-xs"><div><dt className="text-white/30">Edition</dt><dd className="mt-2">Configurable edition of 25</dd></div><div><dt className="text-white/30">Rights review</dt><dd className="mt-2">Passed · demo record</dd></div><div><dt className="text-white/30">Region</dt><dd className="mt-2">{artwork.region}</dd></div><div><dt className="text-white/30">Mood</dt><dd className="mt-2">{artwork.mood}</dd></div></dl></div></div></section>
    {related.length > 0 && <section className="px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1450px]"><p className="eyebrow text-[#c8a968]">Continue looking</p><h2 className="mt-4 font-display text-5xl">Related works</h2><div className="mt-10 grid gap-7 md:grid-cols-3">{related.slice(0,3).map((item) => <ArtworkCard key={item.id} artwork={item}/>)}</div></div></section>}
  </>;
}
