"use client";

import Link from "next/link";
import { Check, X } from "lucide-react";
import { artworks, money } from "@/components/site/catalog";
import { useExperience } from "@/components/site/experience-provider";
import { EmptyState, PageHero } from "@/components/site/page-elements";

export function ComparisonView() {
  const { compare, toggleCompare, addToCart } = useExperience(); const selected = artworks.filter((artwork) => compare.includes(artwork.id));
  if (!selected.length) return <><PageHero compact eyebrow="Side by side" title="Compare works" description="Select up to three works in the catalog to compare scale, medium, mood, licensing, and price."/><div className="px-5 py-20"><EmptyState title="Your comparison is empty" copy="Use the scale icon on any work to place it here." action="Browse the catalog" href="/art"/></div></>;
  return <><PageHero compact eyebrow="Collector tool" title="Compare works" description="A clear view of the details that matter. Prices reflect the catalog’s base configuration."/><section className="overflow-x-auto px-5 py-16 lg:px-10"><div className="mx-auto min-w-[760px] max-w-6xl"><div className="grid" style={{ gridTemplateColumns: `180px repeat(${selected.length},minmax(190px,1fr))` }}><div/>{selected.map((artwork) => <div key={artwork.id} className="border-l border-white/10 p-5"><div className="h-44 bg-cover bg-center" style={{ backgroundImage: `url(${artwork.image})` }}/><div className="mt-5 flex justify-between gap-3"><div><p className="font-display text-2xl">{artwork.title}</p><p className="mt-2 text-xs text-white/45">{artwork.artist}</p></div><button onClick={() => toggleCompare(artwork.id)} aria-label={`Remove ${artwork.title}`}><X size={15}/></button></div></div>)}{[["Price", (art: typeof artworks[number]) => money(art.priceCents)], ["Medium", (art: typeof artworks[number]) => art.medium], ["Dimensions", (art: typeof artworks[number]) => art.dimensions], ["Mood", (art: typeof artworks[number]) => art.mood], ["Living art", (art: typeof artworks[number]) => art.living ? "Yes" : "Static edition"], ["Commercial license", (art: typeof artworks[number]) => art.commercialLicense ? "Eligible" : "No"]].map(([label, getter]) => <div className="contents" key={label as string}><div className="border-t border-white/10 p-5 text-[10px] uppercase tracking-widest text-white/35">{label as string}</div>{selected.map((artwork) => <div key={artwork.id} className="border-l border-t border-white/10 p-5 text-sm text-white/65">{(getter as (art: typeof artwork) => string)(artwork)}</div>)}</div>)}<div/><>{selected.map((artwork) => <div key={artwork.id} className="border-l border-t border-white/10 p-5"><button onClick={() => addToCart(artwork)} className="flex w-full items-center justify-center gap-2 bg-[#c8a968] p-3 text-[10px] font-bold uppercase tracking-widest text-black"><Check size={13}/>Select this work</button><Link href={`/art/${artwork.slug}`} className="mt-2 block border border-white/15 p-3 text-center text-[10px] uppercase tracking-widest">View details</Link></div>)}</></div></div></section></>;
}
