"use client";

import { useState } from "react";
import { Check, LoaderCircle, Sparkles } from "lucide-react";
const stages = ["Brief", "Cultural review", "Composition", "Rights check", "Curatorial review"];
export function StudioDemo() {
  const [brief, setBrief] = useState("A restorative landscape for a quiet hotel suite, mineral blue and warm limestone, broad horizontal composition"); const [stage, setStage] = useState(-1); const [complete, setComplete] = useState(false);
  const generate = () => { setComplete(false); setStage(0); let index = 0; const timer = window.setInterval(() => { index += 1; if (index >= stages.length) { window.clearInterval(timer); setComplete(true); setStage(-1); } else setStage(index); }, 420); };
  return <div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><div className="surface p-6 md:p-9"><p className="eyebrow text-[#c8a968]">Commission brief</p><h2 className="mt-4 font-display text-4xl">Describe the feeling, not an artist to copy.</h2><label className="mt-8 block text-[10px] uppercase tracking-widest text-white/40">Creative direction<textarea value={brief} onChange={(event) => setBrief(event.target.value)} className="mt-3 min-h-36 w-full border border-white/12 bg-white/5 p-4 text-sm normal-case leading-7 text-white"/></label><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-[10px] uppercase tracking-widest text-white/40">Format<select className="mt-2 w-full bg-[#24211c] p-3 text-xs normal-case text-white"><option>Landscape</option><option>Portrait</option><option>Square</option></select></label><label className="text-[10px] uppercase tracking-widest text-white/40">Intended space<select className="mt-2 w-full bg-[#24211c] p-3 text-xs normal-case text-white"><option>Hospitality</option><option>Home</option><option>Office</option></select></label></div><button onClick={generate} disabled={!brief.trim() || stage >= 0} className="mt-6 flex w-full items-center justify-center gap-2 bg-[#c8a968] p-4 text-[10px] font-bold uppercase tracking-widest text-black disabled:opacity-50">{stage >= 0 ? <LoaderCircle className="animate-spin" size={15}/> : <Sparkles size={15}/>} {stage >= 0 ? "Building concept" : "Generate concept study"}</button><p className="mt-4 text-[10px] leading-5 text-white/30">Demo generation creates no billable provider request. Public release and physical production require human approval.</p></div>
    <div className="relative min-h-[600px] overflow-hidden bg-[radial-gradient(circle_at_35%_35%,#617f8a,transparent_26%),radial-gradient(circle_at_70%_40%,#c6aa79,transparent_26%),linear-gradient(145deg,#1b2528,#6e5946_55%,#d0c5ad)]"><div className="absolute inset-0 bg-[linear-gradient(100deg,transparent_20%,rgba(255,255,255,.08)_45%,transparent_65%)]"/>{complete && <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,transparent,#080706aa)]"/>}<div className="absolute bottom-0 left-0 right-0 bg-black/70 p-6 backdrop-blur"><p className="eyebrow text-[#d9bd7a]">{complete ? "Concept study ready" : stage >= 0 ? `Guide workflow · ${stages[stage]}` : "Waiting for your brief"}</p><div className="mt-4 flex gap-2">{stages.map((label,index) => <div key={label} className="flex-1"><div className={`h-1 ${complete || index <= stage ? "bg-[#c8a968]" : "bg-white/12"}`}/><p className="mt-2 hidden text-[8px] uppercase tracking-wider text-white/35 sm:block">{label}</p></div>)}</div>{complete && <p className="mt-5 flex items-center gap-2 text-xs text-white/65"><Check size={14} className="text-emerald-300"/>Demo concept passed simulated cultural, safety, and rights review.</p>}</div></div></div>;
}
