"use client";

import { useState } from "react";
import { Check, ChevronDown, Move, Save, Share2, SlidersHorizontal } from "lucide-react";
import { artworks, environments } from "@/components/site/catalog";

const wallValues: Record<string,string> = { "warm white": "#d8d0c0", "deep olive": "#41473a", clay: "#a66f55", limestone: "#b7ac99", "soft grey": "#908f8a", ink: "#232526", plaster: "#cec4b2", "dusty blue": "#64717b", umber: "#60483b" };
export function RoomPreview({ initialSlug }: { initialSlug?: string }) {
  const [artId, setArtId] = useState(artworks.find((artwork) => artwork.slug === initialSlug)?.id || artworks[0].id);
  const [environmentId, setEnvironmentId] = useState(environments[0].id); const environment = environments.find((item) => item.id === environmentId) || environments[0];
  const [wall, setWall] = useState(environment.wallColors[0]); const [lighting, setLighting] = useState("Daylight"); const [frame, setFrame] = useState("Slim black"); const [size, setSize] = useState(48); const [x, setX] = useState(50); const [saved, setSaved] = useState(false); const [shared, setShared] = useState(false); const artwork = artworks.find((item) => item.id === artId) || artworks[0];
  const changeEnvironment = (id: string) => { const next = environments.find((item) => item.id === id); setEnvironmentId(id); if (next) setWall(next.wallColors[0]); };
  return <section className="px-5 py-12 lg:px-10"><div className="mx-auto grid max-w-[1500px] gap-5 xl:grid-cols-[330px_1fr]">
    <aside className="surface p-5"><div className="flex items-center gap-2"><SlidersHorizontal size={16} className="text-[#c8a968]"/><p className="eyebrow text-[#c8a968]">Preview controls</p></div><div className="mt-7 space-y-6">
      <label className="block text-[10px] uppercase tracking-widest text-white/40">Artwork<select value={artId} onChange={(event) => setArtId(event.target.value)} className="mt-2 w-full bg-[#24211c] p-3 text-xs normal-case text-white">{artworks.slice(0,30).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>
      <label className="block text-[10px] uppercase tracking-widest text-white/40">Environment<select value={environmentId} onChange={(event) => changeEnvironment(event.target.value)} className="mt-2 w-full bg-[#24211c] p-3 text-xs normal-case text-white">{environments.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.type}</option>)}</select></label>
      <fieldset><legend className="text-[10px] uppercase tracking-widest text-white/40">Wall color</legend><div className="mt-3 flex flex-wrap gap-2">{environment.wallColors.map((color) => <button key={color} onClick={() => setWall(color)} title={color} aria-label={`Set wall color to ${color}`} className={`size-9 rounded-full border-2 ${wall === color ? "border-[#c8a968]" : "border-transparent"}`} style={{ background: wallValues[color] || "#aaa" }}/>)}</div></fieldset>
      <label className="block text-[10px] uppercase tracking-widest text-white/40">Lighting<select value={lighting} onChange={(event) => setLighting(event.target.value)} className="mt-2 w-full bg-[#24211c] p-3 text-xs normal-case text-white"><option>Daylight</option><option>Gallery spots</option><option>Evening ambient</option><option>Soft indirect</option></select></label>
      <label className="block text-[10px] uppercase tracking-widest text-white/40">Frame<select value={frame} onChange={(event) => setFrame(event.target.value)} className="mt-2 w-full bg-[#24211c] p-3 text-xs normal-case text-white"><option>Slim black</option><option>Natural oak</option><option>Champagne metal</option><option>Gallery white</option><option>Unframed</option></select></label>
      <label className="block text-[10px] uppercase tracking-widest text-white/40">Artwork size · {size} in<input type="range" min="24" max="74" value={size} onChange={(event) => setSize(Number(event.target.value))} className="mt-3 w-full accent-[#c8a968]"/></label><label className="block text-[10px] uppercase tracking-widest text-white/40">Wall position<input type="range" min="27" max="73" value={x} onChange={(event) => setX(Number(event.target.value))} className="mt-3 w-full accent-[#c8a968]"/></label>
    </div><div className="mt-8 grid grid-cols-2 gap-2"><button onClick={() => setSaved(true)} className="flex items-center justify-center gap-2 border border-white/15 p-3 text-[10px] uppercase tracking-widest">{saved ? <Check size={14}/> : <Save size={14}/>} {saved ? "Saved" : "Save"}</button><button onClick={() => { navigator.clipboard?.writeText(window.location.href); setShared(true); }} className="flex items-center justify-center gap-2 border border-white/15 p-3 text-[10px] uppercase tracking-widest"><Share2 size={14}/>{shared ? "Copied" : "Share"}</button></div><a href="/contact?subject=design-consultation" className="mt-2 block bg-[#c8a968] p-3 text-center text-[10px] font-bold uppercase tracking-widest text-black">Request design consultation</a>
    </aside>
    <div className="relative min-h-[640px] overflow-hidden" style={{ background: `linear-gradient(180deg,${wallValues[wall] || "#bdb6aa"} 0 66%,#66584b 66% 69%,#3d342c 69%)` }}>
      <div className={`absolute inset-0 pointer-events-none ${lighting === "Evening ambient" ? "bg-[#462c1a]/35" : lighting === "Gallery spots" ? "bg-[radial-gradient(circle_at_50%_8%,rgba(255,248,218,.5),transparent_42%)]" : lighting === "Soft indirect" ? "bg-white/10" : "bg-[linear-gradient(110deg,rgba(255,255,255,.28),transparent_35%)]"}`}/><div className="absolute left-[8%] top-[11%] h-[55%] w-[22%] border-[10px] border-[#282522] bg-[linear-gradient(135deg,#9ab3bd,#d8cdb4)] opacity-60"/><div className="absolute bottom-[10%] left-[12%] h-[18%] w-[35%] rounded-t-3xl bg-[#827a6d] shadow-2xl"/><div className="absolute bottom-[10%] right-[11%] h-[25%] w-[28%] bg-[#4e483f] shadow-2xl"/><div className="absolute bottom-[9%] left-[46%] h-[5%] w-[21%] rounded-full bg-black/25 blur-lg"/>
      <div className={`absolute top-[21%] -translate-x-1/2 bg-[#13110e] p-[7px] shadow-[0_24px_55px_rgba(0,0,0,.45)] transition-all duration-300 ${frame === "Natural oak" ? "bg-[#7a5737]" : frame === "Champagne metal" ? "bg-[#b69b68]" : frame === "Gallery white" ? "bg-[#e2ddd2]" : frame === "Unframed" ? "p-0" : ""}`} style={{ left: `${x}%`, width: `${size * 6.4}px`, maxWidth: "57%" }}><div className="aspect-[4/3] bg-cover bg-center" style={{ backgroundImage: `url(${artwork.image})` }}/></div>
      <div className="absolute bottom-5 left-1/2 flex -translate-x-1/2 items-center gap-3 rounded-full bg-black/65 px-4 py-2 text-[10px] text-white/60 backdrop-blur"><Move size={13}/>Perspective-aware placement is simulated in this preview<ChevronDown size={13}/></div>
    </div>
  </div></section>;
}
