"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Box, CirclePause, Lightbulb, Map, Play, Sparkles } from "lucide-react";
import type { GalleryRoom, Artwork } from "@/types";
import { ArtworkCard } from "@/components/artwork/artwork-card";
import { rooms } from "@/components/site/catalog";

export function RoomExperience({ room, roomArtworks }: { room: GalleryRoom; roomArtworks: Artwork[] }) {
  const [mode, setMode] = useState<"cinematic" | "spatial">("cinematic");
  const [lighting, setLighting] = useState<"day" | "dusk" | "focus">("dusk");
  const [touring, setTouring] = useState(false);
  const index = rooms.findIndex((item) => item.id === room.id);
  const previous = rooms[(index - 1 + rooms.length) % rooms.length]; const next = rooms[(index + 1) % rooms.length];
  const roomGlow = lighting === "day" ? "rgba(229,221,193,.2)" : lighting === "focus" ? `${room.accent}3d` : "rgba(171,102,62,.15)";
  return <>
    <section className="relative isolate min-h-[76vh] overflow-hidden border-b border-white/10 px-5 py-12 lg:px-10" style={{ background: `radial-gradient(circle at 50% 20%,${roomGlow},transparent 35%),linear-gradient(180deg,#181511,#090807)` }}>
      <div aria-hidden className="absolute inset-x-[9%] bottom-0 top-[21%] -z-10 border-x border-t border-white/10"/><div aria-hidden className="absolute bottom-0 left-[18%] right-[18%] -z-10 h-[56%] [clip-path:polygon(30%_0,70%_0,100%_100%,0_100%)]" style={{ background: `linear-gradient(180deg,${room.accent}0a,${room.accent}30)` }}/>
      <div className="mx-auto flex max-w-[1450px] flex-col justify-between gap-16 min-h-[64vh]"><div className="flex flex-wrap items-center justify-between gap-4"><Link href="/gallery" className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-white/50"><ArrowLeft size={14}/>All rooms</Link><div className="flex flex-wrap gap-2"><button onClick={() => setMode("cinematic")} className={`px-4 py-2 text-[10px] uppercase tracking-widest ${mode === "cinematic" ? "bg-[#e9e3d7] text-black" : "border border-white/15"}`}>2D cinematic</button><button onClick={() => setMode("spatial")} className={`flex items-center gap-2 px-4 py-2 text-[10px] uppercase tracking-widest ${mode === "spatial" ? "bg-[#e9e3d7] text-black" : "border border-white/15"}`}><Box size={13}/>Spatial preview</button><button onClick={() => setTouring((value) => !value)} className="flex items-center gap-2 border border-[#c8a968]/50 px-4 py-2 text-[10px] uppercase tracking-widest text-[#d9bd7a]">{touring ? <CirclePause size={13}/> : <Play size={13}/>} {touring ? "Pause tour" : "Guided tour"}</button></div></div>
        <div className="mx-auto max-w-4xl text-center"><p className="eyebrow" style={{ color: room.accent }}>{room.atmosphere}</p><h1 className="mt-5 font-display text-6xl font-light leading-[.9] md:text-8xl">{room.name}</h1><p className="mx-auto mt-7 max-w-2xl text-sm leading-7 text-white/52">{room.description}</p>{mode === "spatial" && <p className="mt-5 inline-flex items-center gap-2 bg-white/7 px-4 py-2 text-[10px] uppercase tracking-widest text-white/55"><Sparkles size={13}/>Lightweight spatial simulation · drag controls provider-ready</p>}{touring && <div className="mx-auto mt-6 max-w-xl border border-[#c8a968]/25 bg-black/35 p-4 text-left text-xs leading-6 text-white/60"><span className="text-[#d9bd7a]">Seraphina:</span> Notice first how {room.lighting.toLowerCase()} gathers across {room.material}. This architecture asks us to slow down before approaching the work.</div>}</div>
        <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-2"><Lightbulb size={14} className="text-white/45"/><span className="mr-2 text-[9px] uppercase tracking-widest text-white/35">Lighting</span>{(["day","dusk","focus"] as const).map((value) => <button key={value} onClick={() => setLighting(value)} className={`rounded-full px-3 py-1.5 text-[9px] uppercase tracking-wider ${lighting === value ? "bg-white/15 text-white" : "text-white/35"}`}>{value}</button>)}</div><Link href="/gallery/map" className="flex items-center gap-2 text-[10px] uppercase tracking-widest text-white/45"><Map size={14}/>Room map</Link></div></div>
    </section>
    <section className="px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1250px]"><div className="mb-12 flex items-end justify-between"><div><p className="eyebrow text-[#c8a968]">On view</p><h2 className="mt-3 font-display text-5xl">Works in this room</h2></div><span className="text-xs text-white/35">{roomArtworks.length} works</span></div>{roomArtworks.length ? <div className="space-y-24">{roomArtworks.slice(0, 5).map((artwork, itemIndex) => <div key={artwork.id} className={itemIndex % 2 ? "md:ml-24" : "md:mr-24"}><ArtworkCard artwork={artwork} cinematic/></div>)}</div> : <div className="surface p-16 text-center"><p className="font-display text-4xl">The room is between rotations.</p><p className="mt-4 text-sm text-white/45">Seraphina can guide you to a nearby installation.</p></div>}</div></section>
    <nav className="grid border-y border-white/10 sm:grid-cols-2"><Link href={`/gallery/rooms/${previous.slug}`} className="flex items-center gap-5 border-b border-white/10 px-8 py-8 hover:bg-white/[.025] sm:border-b-0 sm:border-r"><ArrowLeft/><span><span className="eyebrow text-white/35">Previous room</span><span className="mt-2 block font-display text-2xl">{previous.name}</span></span></Link><Link href={`/gallery/rooms/${next.slug}`} className="flex items-center justify-end gap-5 px-8 py-8 text-right hover:bg-white/[.025]"><span><span className="eyebrow text-white/35">Next room</span><span className="mt-2 block font-display text-2xl">{next.name}</span></span><ArrowRight/></Link></nav>
  </>;
}
